name: busybox-builder

on:
  workflow_dispatch:
    inputs:
      version:
        description: BusyBox version without v prefix
        required: true
      sha256:
        description: BusyBox sha256 checksum
        required: true

jobs:
  build-busybox:
    runs-on: ubuntu-latest
    env:
      BUSYBOX_VERSION: ${{ github.event.inputs.version }}
      BUSYBOX_SHA256: ${{ github.event.inputs.sha256 }}
      BUSYBOX_TAG: busybox/v${{ github.event.inputs.version }}
      BUSYBOX_URL: https://busybox.net/downloads/busybox-${{ github.event.inputs.version }}.tar.bz2
    steps:
      - name: Download and build source
        run: |
          echo "Building BusyBox v$BUSYBOX_VERSION [sha256sum=$BUSYBOX_SHA256]"

          # Download source and signature
          curl -fL -o busybox.tar.bz2.sig ${BUSYBOX_URL}.sig
          curl -fL -o busybox.tar.bz2     ${BUSYBOX_URL}

          # Verify signature
          #
          # pub   1024D/ACC9965B 2006-12-12
          #       Key fingerprint = C9E9 416F 76E6 10DB D09D  040F 47B7 0C55 ACC9 965B
          # uid                  Denis Vlasenko <vda.linux@googlemail.com>
          # sub   1024g/2C766641 2006-12-12
          gpg --batch --keyserver keyserver.ubuntu.com --recv-keys C9E9416F76E610DBD09D040F47B70C55ACC9965B
          echo "$BUSYBOX_SHA256 *busybox.tar.bz2" | sha256sum -c -
          gpg --batch --verify busybox.tar.bz2.sig busybox.tar.bz2
          mkdir -p src

          # Extract source
          tar -xf busybox.tar.bz2 -C src --strip-components 1
          rm busybox.tar.bz2*
          cd src

          # Configure busybox
          setConfs='
            CONFIG_AR=y
            CONFIG_FEATURE_AR_CREATE=y
            CONFIG_FEATURE_AR_LONG_FILENAMES=y
            CONFIG_LAST_SUPPORTED_WCHAR=0
            CONFIG_STATIC=y'
          unsetConfs='
            CONFIG_FEATURE_SYNC_FANCY'
          make defconfig
          for conf in $unsetConfs; do
            sed -i \
              -e "s!^$conf=.*\$!# $conf is not set!" \
              .config
          done
          for confV in $setConfs; do
            conf="${confV%=*}"
            sed -i \
              -e "s!^$conf=.*\$!$confV!" \
              -e "s!^# $conf is not set\$!$confV!" \
              .config
            if ! grep -q "^$confV\$" .config; then
              echo "$confV" >> .config
            fi
          done
          make oldconfig

          # Build static binary
          make -j $(nproc) busybox
      - name: Tag for release
        run: |
          git_refs_url=$(jq -r .repository.git_refs_url $GITHUB_EVENT_PATH | sed 's|{/sha}$||')
          curl -s -X POST $git_refs_url \
            -H "Authorization: Token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"ref\":\"refs/tags/$BUSYBOX_TAG\",\"sha\":\"$GITHUB_SHA\"}"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: BusyBox v${{ env.BUSYBOX_VERSION }}
          body: |
            Built from source at ${{ env.BUSYBOX_URL }}

            Checksum=${{ env.BUSYBOX_SHA256 }}
          files: src/busybox
          tag_name: ${{ env.BUSYBOX_TAG }}
